name: Build & Release

# Trigger on push to master branch or with a tag
on:
  push:
    branches:
      - "**"
    tags:
      - "1.*"

# If previous workflow is still running, we push again, we will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: Android
            os: ubuntu-latest
            artifact_name: release-Android
            artifact_path: |
              build/app/outputs/flutter-apk/*-android-arm64-v8a.apk
              build/app/outputs/flutter-apk/*-android-armeabi-v7a.apk
              build/app/outputs/flutter-apk/*-android-x86_64.apk
          - target: Windows
            os: windows-latest
            artifact_name: release-Windows
            artifact_path: |
              build/windows/outputs/*.zip
          - target: Linux
            os: ubuntu-latest
            artifact_name: release-Linux
            artifact_path: |
              build/linux/*.deb
              build/linux/*.tar.gz
          - target: iOS
            os: macos-latest
            cache_pod_key: ios-pods
            cache_pod_path: ios/Pods
            cache_pod_restore_keys_hash_file: ios/Podfile.lock
            artifact_name: release-iOS
            artifact_path: build/**/*.ipa
          - target: MacOS
            os: macos-latest
            cache_pod_key: macos-pods
            cache_pod_path: macos/Pods
            cache_pod_restore_keys_hash_file: macos/Podfile.lock
            artifact_name: release-MacOS
            artifact_path: /Users/runner/work/Honzuki/Honzuki/*.dmg
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      date: ${{ steps.get_version.outputs.date}}
    runs-on: ${{ matrix.os }}
    env:
      FLUTTER_VERSION: 3.24.3
    steps:
      # Checkout branch
      - name: Checkout
        uses: actions/checkout@v4

      # Add Android keystore
      - name: Setup Android keystore
        if: matrix.target == 'Android'
        run: |
          echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 -di > android/app/upload-keystore.jks
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      # Cache Pod
      - name: Cache Pod
        if: matrix.cache_pod_key != null
        uses: actions/cache@v4
        with:
          key: ${{ matrix.cache_pod_key }}
          path: ${{ matrix.cache_pod_path }}
          restore-keys: ${{ matrix.cache_key }}-${{ hashFiles(matrix.cache_pod_restore_keys_hash_file)}}

      # Setup JDK
      - name: Setup JDK 21 (Android)
        if: matrix.target == 'Android'
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: gradle

      # Xcodebuild
      - name: Build Xcode
        if: matrix.os == 'macos-latest'
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release

      # Flutter Pub Get
      - name: Flutter Pub Get
        run: |
          flutter pub get

      # Get app version
      - name: Get app version
        id: get_version
        shell: bash
        run: |
          echo "version=$(head -n 19 pubspec.yaml | tail -n 1 | cut -d ' ' -f 2 | cut -d '+' -f 1)" >> $GITHUB_OUTPUT
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      # Build Android .apk
      - name: Build Android
        if: matrix.target == 'Android'
        run: |
          flutter build apk --release
          flutter build apk --release --split-per-abi
          cd build/app/outputs/flutter-apk
          mv app-arm64-v8a-release.apk Honzuki-${{ steps.get_version.outputs.version }}-android-arm64-v8a.apk
          mv app-armeabi-v7a-release.apk Honzuki-${{ steps.get_version.outputs.version }}-android-armeabi-v7a.apk
          mv app-x86_64-release.apk Honzuki-${{ steps.get_version.outputs.version }}-android-x86_64.apk

      # Build iOS .ipa
      - name: Build iOS
        if: matrix.target == 'iOS'
        run: |
          cd ios
          pod update
          cd ..
          flutter build ios --release --no-codesign
          sh assets/ios/thin_payload.sh build/ios/iphoneos/*.app
          cd build
          mkdir -p Payload
          mv ios/iphoneos/*.app Payload
          zip -9 Honzuki-${{ steps.get_version.outputs.version }}-ios.ipa -r Payload

      # Build MacOS .dmg
      - name: Build MacOS
        if: matrix.target == 'MacOS'
        run: |
          cd macos
          pod update
          cd ..
          flutter build macos --release
          hdiutil create -format UDZO -srcfolder build/macos/Build/Products/Release/honzuki.app -volname Honzuki Honzuki-${{ steps.get_version.outputs.version }}-macos-universal.dmg

      # Build Windows .zip
      - name: Build Windows
        if: matrix.target == 'Windows'
        run: |
          flutter build windows --release
          $DestDir = "build\windows\outputs\Honzuki-${{ steps.get_version.outputs.version }}-windows-x86_64"
          $SrcDir = "build\windows\x64\runner\Release"

          Copy-Item -Filter *.dll -Path windows\* -Destination $DestDir -Force
          New-Item -Path $DestDir -ItemType Directory
          Copy-Item $SrcDir\* -Recurse $DestDir

          Compress-Archive $DestDir build\windows\outputs\Honzuki-${{ steps.get_version.outputs.version }}-windows-x86_64.zip

      # Build Linux .deb
      - name: Build Linux
        if: matrix.target == 'Linux'
        run: |
          # Prepare build depends
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y clang cmake ninja-build pkg-config liblzma-dev libgtk-3-dev liblzma-dev libstdc++-12-dev

          # Compile
          flutter config --enable-linux-desktop
          flutter build linux --release

          # Debian package
          mkdir -p build/linux/Honzuki-${{ steps.get_version.outputs.version }}-linux-amd64
          cd build/linux/Honzuki-${{ steps.get_version.outputs.version }}-linux-amd64
          mkdir -p opt/Honzuki
          mkdir -p usr/share/metainfo
          mkdir -p usr/share/applications
          mkdir -p usr/share/icons/hicolor/512x512/apps
          cp -r ../x64/release/bundle/* opt/Honzuki
          cp -r ../../../assets/linux/DEBIAN .
          chmod 0755 DEBIAN/postinst
          chmod 0755 DEBIAN/postrm

          cat>DEBIAN/control<<EOF
          Maintainer: Pugaizai <i@pugai.life>
          Package: Honzuki
          Version: ${{ steps.get_version.outputs.version }}
          Section: x11
          Priority: optional
          Architecture: amd64
          Essential: no
          Installed-Size: 25944
          Description: A light novel reader for wenku8.net.
          Homepage: https://github.com/pugaizai/honzuki
          Depends: libglu1-mesa
          EOF

          sed -i '29i\    <release version="${{ steps.get_version.outputs.version }}" date="${{ steps.get_version.outputs.date }}">' ../../../assets/linux/life.pugai.honzuki.metainfo.xml
          cp ../../../assets/linux/life.pugai.honzuki.metainfo.xml usr/share/metainfo
          cp ../../../assets/linux/life.pugai.honzuki.desktop usr/share/applications
          cp ../../../assets/icon/icon_512.png usr/share/icons/hicolor/512x512/apps/life.pugai.honzuki.png

          sed -i "/^Version: /s/Version: .*/Version: ${{ steps.get_version.outputs.version }}/" DEBIAN/control

          cd ..
          dpkg-deb --build --root-owner-group Honzuki-${{ steps.get_version.outputs.version }}-linux-amd64
          tar -zcvf Honzuki-${{ steps.get_version.outputs.version }}-linux-amd64.tar.gz -C Honzuki-${{ steps.get_version.outputs.version }}-linux-amd64 .

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}

  Publish:
    if: startsWith(github.ref, 'refs/tags/')
    name: Publish
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get app version
        id: get_version
        shell: bash
        run: |
          echo "version=$(head -n 19 pubspec.yaml | tail -n 1 | cut -d ' ' -f 2 | cut -d '+' -f 1)" >> $GITHUB_OUTPUT
      - name: Make tmp dir
        run: mkdir /tmp/artifacts
      - name: Download all Artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts
      - name: List and move all Artifacts
        run: |
          mkdir -p /tmp/artifacts/final
          mv /tmp/artifacts/release-Android/*.apk /tmp/artifacts/final/
          mv /tmp/artifacts/release-Windows/*.zip /tmp/artifacts/final/
          mv /tmp/artifacts/release-MacOS/*.dmg /tmp/artifacts/final/
          mv /tmp/artifacts/release-iOS/*.ipa /tmp/artifacts/final/
          mv /tmp/artifacts/release-Linux/*.deb /tmp/artifacts/final/
          mv /tmp/artifacts/release-Linux/*.tar.gz /tmp/artifacts/final/

          ls -R /tmp/artifacts/final

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          artifacts: /tmp/artifacts/final/*
          artifactErrorsFailBuild: true
          replacesArtifacts: true
